version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: monday
      time: "06:47"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    rebase-strategy: auto
    groups:
      actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: chore(actions)
